<script lang="ts">
	import { onMount } from 'svelte';

	// run blob
	onMount(() => {
		let cleanup: (() => void) | null = null;
		let mounted = true;

		// async function to load p5 and initialize sketch
		const initializeSketch = async () => {
			// dynamically import p5 only in the browser
			const { default: p5 } = await import('p5');

			// make p5 available globally for the sketch files
			if (!(window as any).p5) {
				(window as any).p5 = p5;
			}

			const tryMount = () => {
				if (!mounted) return;

				if (window.mountBlobSketch) {
					cleanup = window.mountBlobSketch('blob-component-container');
				} else {
					setTimeout(tryMount, 50);
				}
			};

			tryMount();
		};

		initializeSketch();

		return () => {
			mounted = false;
			if (cleanup) cleanup();
		};
	});
</script>

<svelte:head>
	<title>blob</title>
	<meta
		name="description"
		content="blob was an installation designed to examine sound-based interaction for digital
			installations. It picked up a spectrum of frequencies and mapped them to its rings according
			to their loudness, coupled with movement generated by randomness and noise."
	/>
	<script src="/sketches/blob/blob.js" defer></script>
</svelte:head>

<main
	class="font-consolas m-0 min-h-screen overflow-hidden overflow-x-hidden bg-white px-6 pt-12 pb-5 text-black"
>
	<article class="bg-opacity-90 relative z-10 bg-white px-5 md:bg-transparent">
		<div class="mb-5 flex items-center justify-center text-center">
			<div class="flex-1 text-center">
				<h1 class="mb-0 pb-1 text-center text-4xl font-bold">blob</h1>
				<div class="mt-1 text-xl">
					<time class="text-xl">2020</time>
					<span> | p5.js | interactive installation</span>
				</div>
			</div>
		</div>

		<p class="mb-4 md:mb-0">
			blob was an installation designed to examine sound-based interaction for digital
			installations. It picked up a spectrum of frequencies and mapped them to its rings according
			to their loudness, coupled with movement generated by randomness and noise.
			<br />
			<br />
			It was made as a thesis project at Hochschule Bremen. Here it just lives as a neat little animation.
		</p>

		<!-- p5 sketch container -->
		<div
			id="blob-component-container"
			class="responsive-overlap relative md:-mt-[20vh] md:aspect-square md:w-full"
		></div>

		<div class="my-5 md:hidden"></div>
	</article>

	<!-- mobile-only spacer -->
	<!-- <div class="h-12 md:hidden"></div> -->
</main>

<style>
	/* only apply negative margins on desktop (larger screens) */
	@media (min-width: 1000px) {
		.responsive-overlap {
			margin-bottom: -100px !important;
		}
	}

	/* mobile styles with Safari-specific fixes for Blob canvas - can't get this to work with tailwind only */
	@media (max-width: 999px) {
		.responsive-overlap {
			/* use fixed positioning to escape scroll containers */
			position: absolute;
			top: 65vh; /* adjust this value to move sketch up/down */
			left: 0;
			right: 0;
			bottom: 0;
			width: 100vw;
			max-width: 100vw;
			margin: 0 !important;
			z-index: -1; /* behind all content */
			pointer-events: none; /* allow scrolling through */
		}
	}
</style>
