<script lang="ts">
	import FeedbackCubeReel from '$lib/assets/media/feedback_cube/feedback_cube_reel.webm';
	import FeedbackCubeReelMP4 from '$lib/assets/media/feedback_cube/feedback_cube_reel.mp4';
	import FeedbackCube1 from '$lib/assets/media/feedback_cube/feedback_cube_1.jpg?enhanced';
	import FeedbackCube2 from '$lib/assets/media/feedback_cube/feedback_cube_2.jpg?enhanced';
	import FeedbackCube3 from '$lib/assets/media/feedback_cube/feedback_cube_3.jpg?enhanced';
	import FeedbackCube4 from '$lib/assets/media/feedback_cube/feedback_cube_4.jpg?enhanced';
	import FeedbackCube5 from '$lib/assets/media/feedback_cube/feedback_cube_5.jpg?enhanced';
	import FeedbackCube6 from '$lib/assets/media/feedback_cube/feedback_cube_6.jpg?enhanced';

	let cyclingImagesIndex = $state(0);

	$effect(() => {
		// cycle through images every 3 seconds
		const imageInterval = setInterval(() => {
			cyclingImagesIndex = (cyclingImagesIndex + 1) % 3; // 3 images for cycling
		}, 3000);

		return () => clearInterval(imageInterval);
	});

	const cyclingImages = [FeedbackCube1, FeedbackCube4, FeedbackCube2];
</script>

<svelte:head>
	<title>feedback_cube</title>
	<meta
		name="description"
		content="feedback_cube is an interactive audiovisual installation driven by seeming randomness that
			explores the temporal associations of visual and auditory noise."
	/>
</svelte:head>

<main class="font-consolas m-0 min-h-screen bg-[rgb(42,0,25)] px-6 pt-12 pb-5 text-white">
	<article class="px-5">
		<div class="mb-5 flex items-center justify-center text-center">
			<div class="flex-1 text-center">
				<h1 class="mb-0 pb-1 text-center text-4xl font-bold">feedback_cube</h1>
				<div class="mt-1 text-xl text-white">
					<time class="text-xl">2022</time>
					<span> | interactive installation | Processing | Max/MSP</span>
				</div>
			</div>
		</div>

		<p class="mb-1 text-center">
			in collaboration with <a
				href="http://www.chihimchik.com/"
				class="text-white underline hover:text-[rgb(238,130,238)]">Chi Him Chik</a
			>
		</p>

		<p class="mb-1 text-center">
			photos by <a
				href="https://www.jimiliu.com/"
				class="text-white underline hover:text-[rgb(238,130,238)]">Jimmy Liu</a
			>
		</p>

		<div class="my-5"></div>

		<p>
			feedback_cube is an interactive audiovisual installation driven by randomness that explores
			the temporal associations of visual and auditory noise. The audio output is generated by Aiii
			- an audio improvisation machine - using data from the analysis of the installation's
			surroundings through its microphone input. A Processing program generates the visual
			representations of Aiii's data and is in turn sending scrambled data points back to Aiii,
			creating a controlled feedback loop.
		</p>

		<div class="my-5"></div>

		<figure class="relative m-0 p-0">
			{#each cyclingImages as image, index}
				<enhanced:img
					src={image}
					alt="feedback_cube"
					class="block w-full {index === cyclingImagesIndex
						? 'opacity-100'
						: 'opacity-0'} {index === 0 ? 'relative' : 'absolute inset-0'}"
					loading="lazy"
				/>
			{/each}
		</figure>

		<div class="my-5"></div>

		<figure class="m-0 p-0">
			<enhanced:img src={FeedbackCube5} alt="feedback_cube" class="block w-full" loading="lazy" />
		</figure>

		<div class="my-5"></div>

		<div class="flex flex-col gap-4 md:flex-row">
			<figure class="m-0 flex p-0">
				<enhanced:img src={FeedbackCube3} alt="feedback_cube" class="block" loading="lazy" />
			</figure>

			<figure class="m-0 flex p-0">
				<enhanced:img src={FeedbackCube6} alt="feedback_cube" class="block" loading="lazy" />
			</figure>
		</div>

		<div class="my-5"></div>

		<figure class="m-0 p-0">
			<video
				title="feedback_cube reel video"
				class="block h-auto w-full object-cover"
				controls
				muted
				autoplay
				loop
				preload="auto"
			>
				<source src={FeedbackCubeReel} type="video/webm" />
				<source src={FeedbackCubeReelMP4} type="video/mp4" />
				Your browser does not support the video tag.
			</video>
		</figure>

		<div class="my-5"></div>
	</article>

	<!-- mobile-only spacer -->
	<div class="h-12 md:hidden"></div>
</main>
