<script lang="ts">
	import { browser } from '$app/environment';
	import { onMount, onDestroy } from 'svelte';
	import { beforeNavigate } from '$app/navigation';

	const cleanup = () => {
		if (browser && window.cleanupBlobSketch) {
			window.cleanupBlobSketch();
			delete window.cleanupBlobSketch;
		}
		if (browser) {
			window.blobSketchInitialized = undefined;
		}
	};

	const loadBlobSketch = async () => {
		if (!browser) return;

		// load p5.js if not already loaded
		if (!(window as any).p5) {
			await new Promise((resolve) => {
				const script = document.createElement('script');
				script.src = '/libs/p5_v0.10.2.min.js';
				script.onload = resolve;
				document.head.appendChild(script);
			});
		}

		// always reset the flag and load the sketch
		window.blobSketchInitialized = undefined;

		// load the blob sketch script
		await new Promise((resolve) => {
			const script = document.createElement('script');
			script.src = '/sketches/blob/blob.js';
			script.onload = resolve;
			document.head.appendChild(script);
		});
	};

	onMount(() => {
		// Wait a bit for the DOM to be fully ready
		setTimeout(() => {
			loadBlobSketch();
		}, 100);
	});

	beforeNavigate(cleanup);
	onDestroy(cleanup);
</script>

<svelte:head>
	<meta name="description" content="blob" />
</svelte:head>

<main class="font-consolas m-0 min-h-screen bg-white px-6 pt-12 pb-5 text-black">
	<article class="px-5">
		<div class="mb-5 flex items-center justify-center text-center">
			<div class="flex-1 text-center">
				<h1 class="mb-0 pb-1 text-center text-4xl font-normal">Blob</h1>
				<div class="mt-1 text-xl">
					<time class="text-xl">2020</time>
					<span> | p5.js | interactive installation</span>
				</div>
			</div>
		</div>

		<p class="mb-4 md:mb-0">
			Blob was an installation designed to examine sound-based interaction for digital
			installations. It picked up a spectrum of frequencies and mapped them to its rings according
			to their loudness, coupled with movement generated by randomness and noise.
			<br />
			<br />
			It was made as a thesis project at Hochschule Bremen. Here it just lives as a neat little animation.
		</p>

		<div
			id="blob-container"
			class="responsive-overlap relative ml-[calc(-50vw+50%)] aspect-square w-screen md:-mt-[200px] md:ml-0 md:w-full"
		></div>

		<div class="my-5"></div>
	</article>
</main>

<style>
	/* only apply negative margins on desktop (larger screens) */
	@media (min-width: 768px) {
		.responsive-overlap {
			margin-bottom: -100px !important;
		}
	}
</style>
