<script lang="ts">
</script>

<svelte:head>
	<meta name="description" content="blob" />
	<script src="/../libs/p5_v0.10.2.min.js"></script>
	<script src="/sketches/blob/blob.js"></script>
</svelte:head>

<main class="font-consolas m-0 min-h-screen bg-white px-7 pt-12 pb-5 text-black">
	<article class="px-5">
		<div class="mb-5 flex items-center justify-center text-center">
			<div class="flex-1 text-center">
				<h1 class="mb-0 pb-1 text-center text-2xl font-normal">Blob</h1>
				<div class="mt-1 text-sm">
					<time class="text-sm">2020</time>
					<span> | p5.js | interactive installation</span>
				</div>
			</div>
		</div>

		<div class="text-2xs">
			<p class="mb-4">
				Blob was an installation designed to examine sound-based interaction for digital
				installations. It picked up a spectrum of frequencies and mapped them to its rings according
				to their loudness, coupled with movement generated by randomness and noise.
				<br />
				<br />
				It was made as a thesis project at Hochschule Bremen. Here it just lives as a neat little animation.
			</p>

			<div class="my-5"></div>

			<div id="blob-container" class="aspect-square w-full"></div>

			<div class="my-5"></div>
		</div>
	</article>
</main>
