<script>
</script>

<svelte:head>
	<title>feedback_cube</title>
	<meta name="description" content="feedback_cube" />
</svelte:head>

<main
	class="font-consolas max-w-[950p m-0 mx-auto min-h-screen bg-[rgb(42,0,25)] px-0 pt-12 pb-5 text-white md:px-2"
>
	<article class="px-0 md:px-2">
		<div class="mb-5 flex items-center justify-center px-2 text-center md:px-0">
			<div class="flex-1 text-center">
				<h1 class="mb-0 pb-1 text-center text-2xl font-normal">feedback_cube</h1>
				<div class="mt-1 text-sm text-white">
					<time class="text-sm">2022</time>
					<span> | interactive installation | Processing | Max/MSP</span>
				</div>
			</div>
		</div>

		<div class="text-2xs">
			<p class="mb-1 text-center">
				in collaboration with <a
					href="http://www.chihimchik.com/"
					class="text-white underline hover:text-[rgb(238,130,238)]">Chi Him Chik</a
				>
			</p>

			<p class="mb-1 text-center">
				photos by <a
					href="https://www.jimiliu.com/"
					class="text-white underline hover:text-[rgb(238,130,238)]">Jimmy Liu</a
				>
			</p>

			<div class="my-4"></div>

			<p>
				feedback_cube is an interactive audiovisual installation driven by seeming randomness that
				explores the temporal associations of visual and auditory noise. The audio output is
				generated by Aiii - an audio improvisation machine - using data from the analysis of the
				installation's surroundings through its microphone input. The Processing sketch generates
				the visual content from Aiii's data and is in turn sending scrambled data points back to
				Aiii.
			</p>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<img
					src="/media/feedback_cube/feedback_cube_1.jpg"
					alt="feedback_cube"
					class="block w-full"
				/>
			</figure>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<img
					src="/media/feedback_cube/feedback_cube_4.jpg"
					alt="feedback_cube"
					class="block w-full"
				/>
			</figure>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<img
					src="/media/feedback_cube/feedback_cube_2.jpg"
					alt="feedback_cube"
					class="block w-full"
				/>
			</figure>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<img
					src="/media/feedback_cube/feedback_cube_5_slim.jpg"
					alt="feedback_cube"
					class="block w-full"
				/>
			</figure>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<img
					src="/media/feedback_cube/feedback_cube_6_slim.jpg"
					alt="feedback_cube"
					class="block w-full"
				/>
			</figure>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<img
					src="/media/feedback_cube/feedback_cube_3_slim.jpg"
					alt="feedback_cube"
					class="block w-full"
				/>
			</figure>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<video
					src="media/feedback_cube/feedback_cube_phone.mp4"
					title="feedback_cube phone video"
					class="block h-auto w-full object-cover"
					controls
					muted
					autoplay
					loop
				>
					Your browser does not support the video tag.
				</video>
			</figure>

			<div class="my-4"></div>

			<figure class="m-0 p-0">
				<iframe
					src="https://www.youtube.com/embed/-1TlFn3s8OU"
					title="feedback_cube reel"
					class="block aspect-video w-full"
					frameborder="0"
					allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
					allowfullscreen
				>
				</iframe>
			</figure>

			<div class="my-4"></div>
		</div>
	</article>
</main>
