name: Build and Deploy to Main

on:
  push:
    branches: [sveltekit-static-site]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Pull
        run: |
          git pull

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy to main branch
        run: |
          cp -r build /tmp/build-output

          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main

          cp -r /tmp/build-output/* .

          git add . -f
          git commit -m "Deploy: ${{ github.sha }}"
          git push
